name: GitHub Activity Generator

on:
  schedule:
    - cron: '0 * * * *'  # This will run the activity every hour, adjust if needed
  workflow_dispatch:

jobs:
  generate-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git User
        run: |
          git config --global user.name "girlcodekenya"
          git config --global user.email "rtunguru@gmail.com"

      - name: Generate Fake Activity
        run: |
          echo "Making a fake commit" > activity.txt
          cat activity.txt  # Show contents to confirm it's being written
          git add activity.txt
          git status  # Check if it's staged for commit
          git commit -m "Generated fake activity" || echo "No changes to commit"
          git push || echo "Failed to push changes"
